#!/bin/bash
# Stockr - Development Shortcuts

echo "Stockr Project Commands"
echo "======================="
echo ""
echo "Available commands:"
echo ""
echo "1. Fetch latest data:"
echo "   Rscript R/fetch_data.R"
echo ""
echo "2. Render page locally:"
echo "   quarto render index.qmd"
echo ""
echo "3. View rendered page:"
echo "   # Linux/Mac: open _output/index.html"
echo "   # Windows: start _output/index.html"
echo ""
echo "4. Commit and push changes:"
echo "   git add ."
echo "   git commit -m 'Update: [description]'"
echo "   git push origin main"
echo ""
echo "5. Check database:"
echo "   Rscript -e 'library(duckdb); con <- dbConnect(duckdb(), \"data/stocks.duckdb\"); dbListTables(con)'"
echo ""
echo "GitHub Pages will automatically:"
echo "  ✓ Update data daily at 2 AM UTC"
echo "  ✓ Re-render the page on push to main"
echo "  ✓ Deploy to https://<username>.github.io/stockr/"
echo ""
